name: Build docs

on:
  push:
    branches:
      - main
  pull_request:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    name: Build docs
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: "3.10"

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache
          key: ${{ runner.os }}-${{ hashFiles('requirements*') }}

      - name: Checkout branch being tested
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
          clean: false

      - name: Install dependencies & configure cesium
        run: |
          pip install --upgrade pip
          pip install .

      - name: Build docs
        run: |
          if [[ $SKIP_DOCS != 1 ]]; then
            make doc_reqs
            make html
          fi

      - name: Install SSH Client 🔑
        if: github.ref == 'refs/heads/main'
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.CI_DEPLOY_KEY }}

      - name: Deploy docs
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          FOLDER: doc/_build/html
          REPOSITORY_NAME: cesium-ml/docs
          BRANCH: gh-pages
          SSH: true
