name: Build docs

on:
  push:
    branches: ["main"]
  pull_request:

# Allows you to run this workflow manually from the Actions tab
workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    name: Build docs
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache
            ~/.local
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Checkout branch being tested
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
          clean: false

      - name: Install dependencies & configure cesium
        run: |
          pip install --upgrade pip
          pip install .

      - name: Build docs
        run: |
          if [[ $SKIP_DOCS != 1 ]]; then
            make doc_reqs
            make html
          fi

      - name: Upload docs to pages
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: actions/upload-pages-artifact@v1
        with:
          path: .doc/_build/html
